/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MCard: typeof import('./../src/components/MCard/index.vue')['default']
    MConfigProvider: typeof import('./../src/components/MConfigProvider/index.vue')['default']
    MContent: typeof import('./../src/components/MContent/index.vue')['default']
    MFooter: typeof import('./../src/components/MFooter/index.vue')['default']
    MIcon: typeof import('./../src/components/MIcon/index.vue')['default']
    MImage: typeof import('./../src/components/MImage/index.vue')['default']
    MNavBar: typeof import('./../src/components/MNavBar/index.vue')['default']
    MSafeAreaTop: typeof import('./../src/components/MSafeAreaTop/index.vue')['default']
    MTabBar: typeof import('./../src/components/MTabBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
