/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MButton: typeof import('./../src/components/MButton/index.vue')['default']
    MCard: typeof import('./../src/components/MCard/index.vue')['default']
    MContainer: typeof import('./../src/components/MContainer/index.vue')['default']
    MFooter: typeof import('./../src/components/MFooter/index.vue')['default']
    MIcon: typeof import('./../src/components/MIcon/index.vue')['default']
    MNavBar: typeof import('./../src/components/MNavBar/index.vue')['default']
    MPage: typeof import('./../src/components/MPage/index.vue')['default']
    MSys: typeof import('./../src/components/MSys/index.vue')['default']
    MTabBar: typeof import('./../src/components/MTabBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
